//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MT.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link kích hoạt đã hết hiệu lực. Vui lòng kiểm tra lại..
        /// </summary>
        public static string ErrorExpriedActiveLink {
            get {
                return ResourceManager.GetString("ErrorExpriedActiveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không khớp với Email xác nhận trong hệ thống..
        /// </summary>
        public static string InvalidEmailConfirm {
            get {
                return ResourceManager.GetString("InvalidEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được bỏ trống.
        /// </summary>
        public static string Password_Blank {
            get {
                return ResourceManager.GetString("Password_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn khôi phục mật khẩu.
        /// </summary>
        public static string Title_ActiveLink {
            get {
                return ResourceManager.GetString("Title_ActiveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo mật khẩu đăng nhập hệ thống.
        /// </summary>
        public static string Title_SendLinkActive {
            get {
                return ResourceManager.GetString("Title_SendLinkActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được bỏ trống.
        /// </summary>
        public static string UserName_Blank {
            get {
                return ResourceManager.GetString("UserName_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không tồn tại trong hệ thống..
        /// </summary>
        public static string UserNameInValid {
            get {
                return ResourceManager.GetString("UserNameInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực hết hạn sử dụng..
        /// </summary>
        public static string WarnCodeExpried {
            get {
                return ResourceManager.GetString("WarnCodeExpried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực không hợp lệ..
        /// </summary>
        public static string WarnCodeInValid {
            get {
                return ResourceManager.GetString("WarnCodeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mã xác nhận không được bỏ trống..
        /// </summary>
        public static string WarnUserNameOrCodeBlank {
            get {
                return ResourceManager.GetString("WarnUserNameOrCodeBlank", resourceCulture);
            }
        }
    }
}
